### ISSUE TITLE
No sequencer available for '%s' platform

### ISSUE THREAD

**Issue by vperrinfr** [cognitive-catalyst/watson-beat#1]
Hi, 

I'm trying to test Watson Beat on MacOSX, and when I launched the requirement command, I have that message:

```
Requirement already satisfied: numpy in /Users/vperrin/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Collecting python-midi (from -r requirements.txt (line 2))
  Downloading python-midi-v0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dk/b5g3l6fx2m55fm4knypzcmq80000gn/T/pip-build-c9criuh1/python-midi/setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "No sequencer available for '%s' platform." % platform)?
```

Any ideas ?

Thanks a lot

**Comment by vperrinfr** [comment]
It seems according the Puthn-midi module doesn't work on MacOS or Windows, only on Linux.
[link to github](https://github.com/vishnubob/python-midi/issues/16)

Do you confirm?

**Comment by amchaney** [comment]
hey @vperrinfr looks like it isn't compatible with python 3.6.  I'll have to update the documentation to specify you _must_ use python 2.7.  Everyone who has tested for me was running MACOSX, just FYI.

**Comment by vperrinfr** [comment]
Using Python 2.7. It works fine...

**Comment by ttuanho** [comment]
> hey @vperrinfr looks like it isn't compatible with python 3.6. I'll have to update the documentation to specify you _must_ use python 2.7. Everyone who has tested for me was running MACOSX, just FYI.

Thanks.
