### ISSUE TITLE
"ImportError: No module named requests" — Not importing requests from skeleton.py

### ISSUE THREAD

**Issue by ElectrikPress** [cognitive-catalyst/watson-beat#18]
When running the command for wbDev.py I am getting the above ImportError message when trying to import requests. I verified that I have install requests, have uninstalled it and reinstalled it to troubleshoot and still this is not working. I am using Python 2.7.13. 

Am I installing this in the wrong area? Please let me know. 

Thanks!

**Comment by amchaney** [comment]
Hey ... that is peculiar.  you can check your python by
```
python -V
Python 2.7.13 :: Anaconda 4.3.1 (x86_64)
```
and you can check to see if you have requests installed like
```
pip show requests
Name: requests
Version: 2.13.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /Users/segurson/anaconda2/lib/python2.7/site-packages
Requires: 
Required-by: watson-developer-cloud, textacy, pysolr, conda-build, anaconda-client, Sphinx
```
If you are new to python, I would recommend using anaconda as your distribution since its virtual environments make everything so much easier 😸
