### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by MarlopMerens** [cognitive-catalyst/watson-beat#19]
Hi,
i setup watson beat and it's working fine with the provided midi files but whenever i try using my own midi files i get this error bellow. 

First i stored my midi files on my desktop and used this comand

python2 wbDev.py -i /Users/lucalopez/Desktop/Watson-Beat/Chill.ini -m /Users/lucalopez/Desktop/melody.mid -o /Users/lucalopez/Desktop/Watson-Beat/Midi  

then i tried to store the midi files in the watson beat midi folder and used this comand: 
python2 wbDev.py -i Ini/ReggaePop.ini -m Midi/piere1.mid -o /Users/lucalopez/desktop/

but this doesent work too i tried it with several midi files and also tried to modify a existing midi file but every time im getting this IndexError: 
![screenshot at nov 01 22-28-24](https://user-images.githubusercontent.com/44567359/47881556-cc268480-de26-11e8-8ca8-0249fb1f125d.png)

**Comment by amchaney** [comment]
Hey, this has to do with different formats of midi files. When I record midis for using with this, they need to be a single track.  I use garage band to midi (http://scotttroyer.com/2014/05/export-midi-from-garageband/) which works for me even though it is a bit of a pain.  I would guess whatever you are using to edit the midi files saves them differently than the midi library is expecting.  Try playing around with the midi "save as..." settings and see if you can save as a single track

**Comment by amchaney** [comment]
@MarlopMerens did you manage to create a midi that worked?
