### ISSUE TITLE
'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Shriyash-Jagtap** [cognitive-catalyst/watson-beat#22]
![aaaaaaaaaa](https://user-images.githubusercontent.com/24631484/58167101-d4ea8500-7ca8-11e9-8d3b-fdbfd3a5b2ed.PNG)

when i tried to run wbDev.py i got this error. please help me

**Comment by amblock** [comment]
@shri577 You may need to run it from inside a cygwin shell per these instructions: https://github.com/cognitive-catalyst/watson-beat#special-note-on-running-on-windows--you-will-also-need-to-install-cygwin-as-environment-to-run-the-code-on-all-developmenttesting-of-this-code-was-done-in-nix-systems-and-there-is-something-different-about-the-windows-shell-so-you-need-a-nix-bash-script-emulator-which-is-what-cygwin-is

**Comment by Shriyash-Jagtap** [comment]
thank you for help
