### ISSUE TITLE
Creating actual track

### ISSUE THREAD

**Issue by ghost** [cognitive-catalyst/watson-beat#27]
Hello! Thank you very much for making this library available. I am not a musician, but I have a basic understanding of music, so perhaps that is why I am not sure how to go about creating a track using this library. I am interested in creating a music that I could eventually use to go along with some lyrics. So, I am wondering if we can we use any midi file that is more than a minute long? Specifically, could an input midi file that long help create midi file(s) so as to create a music that could be used for a song? I did run an example that you have under [Ready to Run](https://github.com/cognitive-catalyst/watson-beat#ready-to-run), which is good to understand the elements of the code, but I am looking for some guidance on how I can create my own tracks like those [here](https://soundcloud.com/richarddaskas/sets/tracks-inspired-by-watson-beat) (by Richard Daskas). Although I did go through the [Video Tutorials](https://github.com/cognitive-catalyst/watson-beat#video-tutorials) that helped understand the post-processing with the output midi files, I would appreciate your kind help if you could describe the process on how to go about creating actual tracks (like [this](https://soundcloud.com/richarddaskas/sets/tracks-inspired-by-watson-beat)) using this library that are few minutes long.

**Comment by amchaney** [comment]
Hi,
You need to read the README.md file https://github.com/cognitive-catalyst/watson-beat

The command `python wbDev.py -i Ini/ReggaePop.ini -m Midi/mary.mid -o /Users/Moe/midifiles/` (for example) is when the midis are actually created.  To adjust the length/number of sections/tempo/etc edit the ini file.  To get started, just use one of the midi files checked into the repository. 

As far as creating a "song", there is an example I did with Tayrn Southern https://www.youtube.com/watch?v=bLHid5yyZkM using this code, but there was a TON of post production involved.  The code did create the stems, and Tayrn wrote the lyrics.

**Comment by ghost** [comment]
Hello,

Thanks for your comment, @amchaney. I did try some examples from the repository. Can we use any midi file that is more than a minute long? Would it be computationally advisable in a sense that can the code easily handle that much training data? Thank you!

**Comment by amchaney** [comment]
I have tried different lengths and complexities of midis, I find the short and simple ones work best with this algorithm. The best thing to do is just run the code and try it and see what you get.  I don’t think the code imposed a limit on the midi, but the idea is it is a melody hook and the algorithm riffs on that.

**Comment by ghost** [comment]
Thanks @amchaney!
