### ISSUE TITLE
Mac constantly freezes when setting virtual instruments

### ISSUE THREAD

**Issue by michaela10c** [cognitive-catalyst/watson-beat#9]
Hi!

I have just bought a new MacBook Pro (v. 10.13.2 High Sierra). 

When I try to set virtual instruments on Reaper with this computer, the computer takes a VERY LONG time to buffer. I am able to load instruments into my MIDI files (and play them back successfully), but after every few instruments, the computer stops responding. I constantly had to restart my computer (press down the power key on my keyboard, and press again) in order to get Reaper up and running. And the same issue happens again. And again. 

I have tried uninstalling Reaper and reinstalling it, yet the Mac still had the same buffering issue described above. 

Storage wise, I have 124.11GB available out of 250.69GB. 

Is there any way that this could be fixed? Thank you for your genuine support!

**Comment by amchaney** [comment]
Hi,
Not sure what could be causing this, but I would suggest looking for support in the REAPER forum:
https://forum.cockos.com/forumdisplay.php?f=20
Cheers.
